#!/bin/bash
clear
while true
do

echo "
	NICK justinfan6996
	JOIN #$1
	CAP REQ :twitch.tv/tags
" | netcat irc.chat.twitch.tv 6667 | while read -r LINE
do
	if [ -n "$(echo $LINE | grep -E '(.+) (.+) PRIVMSG #(.+) :(.+)')" ]
	then
		tag=$(echo "$LINE" | awk '{print $1}')
		for pair in $(echo "$tag" | tr ';' '\n')
		do
			pair=$(echo "$pair" | tr '=' ' ')
			name=$(echo "$pair" | awk '{print $1}')
			value=$(echo "$pair" | awk '{print $2}')
			if [ "$name" == "display-name" ]
			then
				display_name=$value
			fi
			if [ "$name" == "color" ]
			then
				color=$(echo $value | sed 's/#//')
			fi
		done
		message=$(echo "$LINE" | sed -E 's/(.+) (.+) PRIVMSG #(.+) :(.+)/\4/')
		printf "\x1b[38;2;%d;%d;%dm%s\x1b[0m %s\n" "0x${color:0:2}" "0x${color:2:2}" "0x${color:4:2}" "$display_name" "$message"
	fi
done

done
