#!/bin/bash
FILTER='^(.+) (.+) PRIVMSG #(\S+) (.+)'

echo $'\033]30;'chat$'\007'

clear
while true
do

echo "
	NICK justinfan6996
	JOIN #$1
	CAP REQ :twitch.tv/tags
" | netcat irc.chat.twitch.tv 6667 | while read -r LINE
do
	filtered=$(echo $LINE | grep -E "$FILTER")
	if [ -n "$filtered" ]
	then
		tag=$(echo "$LINE" | awk '{print $1}')
		for pair in $(echo "$tag" | tr ';' '\n')
		do
			pair=$(echo "$pair" | tr '=' ' ')
			name=$(echo "$pair" | awk '{print $1}')
			value=$(echo "$pair" | awk '{print $2}')
			if [ "$name" == "display-name" ]
			then
				display_name=$value
			fi
			if [ "$name" == "color" ]
			then
				color=$(echo $value | sed -E 's/#([0-9A-F]{6})/\1/')
			fi
		done
		if [ -z "$color" ]
		then
			#echo "warning: bad color $color"
			#echo "$LINE"
			color="FFFF00"
		fi
		message=$(echo "$LINE" | sed -E "s/$FILTER/\4/")
		message="${message:1:9999}"
		printf "\x1b[38;2;%d;%d;%dm%s\x1b[0m %s\n" "0x${color:0:2}" "0x${color:2:2}" "0x${color:4:2}" "$display_name" "$message"
	fi
done

done
